# Generated by Django 5.2.7 on 2025-10-12 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stocks',
            options={},
        ),
        migrations.AddField(
            model_name='stocks',
            name='discount_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Процент скидки'),
        ),
    ]
