# Generated by Django 5.2.7 on 2025-10-12 14:23

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0002_alter_stocks_options_stocks_discount_percent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stocks',
            options={'verbose_name': 'Акция', 'verbose_name_plural': 'Акции'},
        ),
        migrations.AddField(
            model_name='stocks',
            name='first_order_only',
            field=models.BooleanField(default=False, verbose_name='Только для первого заказа'),
        ),
        migrations.AddField(
            model_name='stocks',
            name='min_order_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Минимальная сумма заказа'),
        ),
        migrations.AlterField(
            model_name='stocks',
            name='promo',
            field=models.CharField(max_length=10, unique=True, verbose_name='Промокод'),
        ),
    ]
