# Generated by Django 5.2.7 on 2025-10-09 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bouquet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название букета')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Цена')),
                ('bouquet_type', models.CharField(choices=[('bouquet', 'Букет'), ('box', 'В коробке')], default='bouquet', max_length=10, verbose_name='Тип упаковки')),
                ('flowers_sort', models.CharField(default='', max_length=255, verbose_name='Сорт цветов')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('image', models.ImageField(upload_to='bouquets/', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Букет',
                'verbose_name_plural': 'Букеты',
            },
        ),
    ]
