# Generated by Django 5.2.7 on 2025-10-12 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bouquet',
            name='bouquet_type',
            field=models.CharField(choices=[('bouquet', 'Букет'), ('paper', 'В упаковочной бумаге')], default='bouquet', max_length=10, verbose_name='Тип упаковки'),
        ),
    ]
