# Generated by Django 5.2.7 on 2025-10-12 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_bouquet_bouquet_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bouquet',
            name='bouquet_type',
            field=models.CharField(choices=[('box', 'В коробке'), ('paper', 'В упаковочной бумаге')], default='paper', max_length=10, verbose_name='Тип упаковки'),
        ),
    ]
