# Generated by Django 5.2.7 on 2025-10-12 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='comment',
            field=models.TextField(default='Отсутствует', verbose_name='Комментарий'),
        ),
    ]
