# Generated by Django 5.2.7 on 2025-10-23 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0009_alter_order_phone_number'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PromoCode',
        ),
    ]
